// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgbUOR9uwyxPXgMLDfRa1zEO3g-N3EBPM',
    appId: '1:929150186773:web:6ce69d10fff81df2d1251c',
    messagingSenderId: '929150186773',
    projectId: 'frige2',
    authDomain: 'frige2.firebaseapp.com',
    storageBucket: 'frige2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDafDaU12A67joL2QbZQSdx8Ob8tTMj5lY',
    appId: '1:929150186773:android:594dc9edc66377e2d1251c',
    messagingSenderId: '929150186773',
    projectId: 'frige2',
    storageBucket: 'frige2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmdyKMoJMsAo7lu55R6tbKz69C1Iy-PqY',
    appId: '1:929150186773:ios:c55fdcabe6af9411d1251c',
    messagingSenderId: '929150186773',
    projectId: 'frige2',
    storageBucket: 'frige2.appspot.com',
    iosBundleId: 'com.example.firge2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmdyKMoJMsAo7lu55R6tbKz69C1Iy-PqY',
    appId: '1:929150186773:ios:c55fdcabe6af9411d1251c',
    messagingSenderId: '929150186773',
    projectId: 'frige2',
    storageBucket: 'frige2.appspot.com',
    iosBundleId: 'com.example.firge2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgbUOR9uwyxPXgMLDfRa1zEO3g-N3EBPM',
    appId: '1:929150186773:web:b91236197f4c5bd4d1251c',
    messagingSenderId: '929150186773',
    projectId: 'frige2',
    authDomain: 'frige2.firebaseapp.com',
    storageBucket: 'frige2.appspot.com',
  );
}
